databases:
  - name: cloudEsgi
    databaseName: cloudesgi 
    user: cloudsgi 
    plan: free

services:
  - type: web
    plan: free
    runtime: node
    name: cloudEsgi
    repo:  https://github.com/mazounirayan/serverless
    buildCommand: npm install 
    startCommand: npm run start
    envVars:
      - key: BD
        fromDatabase: 
          name: cloudEsgi
          property: connectionString